server:
  port: 8081
  context-path: /damai

spring:
  datasource:
    master:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/damai?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456
    slave:
      driver-class-name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/damai1?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456
    other:
      driver-Class-Name: com.mysql.jdbc.Driver
      jdbcUrl: jdbc:mysql://localhost:3306/damai?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
      username: root
      password: 123456
mybatis:
  type-aliases-package: com.damai.system.entity
  mapper-locations: classpath*:mapping/*Mapper.xml